# Generated by Django 2.2.24 on 2023-06-28 10:25

from django.db import migrations
from property.models import Flat


def copy_construction_year_to_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = True if flat.construction_year >= 2015 else False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230628_1126'),
    ]

    operations = [
        migrations.RunPython(copy_construction_year_to_new_building)
    ]
