# Generated by Django 2.2.24 on 2023-06-28 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20230628_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(blank=True, null=True, verbose_name='Текст жалобы')),
                ('complain_flat', models.ForeignKey(on_delete='Квартира на которую пожаловались', to='property.Flat')),
                ('complaining_user', models.ForeignKey(on_delete='Кто оставил жалобу', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
