# Generated by Django 2.2.24 on 2023-06-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230628_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complain_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_address', to='property.Flat', verbose_name='Квартира на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaining_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='Кто оставил жалобу'),
        ),
    ]
