# Generated by Django 2.2.24 on 2023-06-29 16:51

from django.db import migrations
import phonenumbers


def create_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for phone in Flat.objects.all():
        parsed_phone = phonenumbers.parse(phone.owners_phonenumber, 'RU')
        phone.owner_pure_phone = phonenumbers.format_number(parsed_phone, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(create_pure_phone)
    ]
