# Generated by Django 2.2.24 on 2023-06-30 07:49

from django.db import migrations


def clone_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for owners in flats.iterator():
        Owner.objects.get_or_create(name=owners.owner, phone=owners.owners_phonenumber,
                                    pure_phone=owners.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner'),
    ]

    operations = [
        migrations.RunPython(clone_owners)
    ]