# Generated by Django 2.2.24 on 2023-07-01 14:07

from django.db import migrations


def clone_owners_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flat.set(Flat.objects.filter(owner=owner.name))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230630_1049'),
    ]

    operations = [
        migrations.RunPython(clone_owners_flat)
    ]
